spring.application.name=stack-overflow-java-analysis
logging.charset.console=UTF-8
logging.charset.file=UTF-8
spring.datasource.url=jdbc:postgresql://localhost:5432/stackoverflow_analysis
spring.datasource.username=postgres
spring.datasource.password=Wzh610709
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

stackoverflow.api.key=rl_2cLVWoXKE828vdnrgaATi88Sg
stackoverflow.api.base-url=https://api.stackexchange.com/2.3
stackoverflow.api.page-size=100
stackoverflow.api.total-threads=1000
stackoverflow.api.tags=java

# 单独的 filter：只返回 question.相关数据（由网页生成）
stackoverflow.api.filter-question=!6FLZiUn1jjumts2_hRQe6Sj25

# 单独的 filter：只返回 answer.相关数据（由网页生成）
stackoverflow.api.filter-answer=!EljoTnJM(Ra6VxcMI.ry**vgC(u.fMKx)jDZe2NGv5

# Spring / 应用日志
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.org.example.stackoverflowjavaanalysis=DEBUG

# 可选：把日志输出到文件 (会在项目根目录生成 logs/app.log)
logging.file.name=logs/app.log
logging.file.max-size=10MB